### ISSUE TITLE
Unable to download Data_ccfsvsse001-backpacks.esl

### ISSUE THREAD

**Issue by tongko** [The-Animonculory/AVO-NG#6]
AVO-NG: version 5

`00:00:13.128 [ERROR] (Wabbajack.Installer.StandardInstaller) Download error for file Data_ccfsvsse001-backpacks.esl|System.NotImplementedException: The method or operation is not implemented.
   at Wabbajack.Downloaders.GameFile.GameFileDownloader.Download(Archive archive, GameFileSource state, AbsolutePath destination, IJob job, CancellationToken token) in c:\oss\wabbajack\Wabbajack.Downloaders.GameFile\GameFileDownloader.cs:line 29
                      (Only first line in stacktrace included)
00:00:13.128 [INFO] (Wabbajack.Installer.StandardInstaller) Next Step: Hashing Archives
00:00:13.128 [INFO] (Wabbajack.Installer.StandardInstaller) Looking for files to hash
00:00:13.128 [INFO] (Wabbajack.Installer.StandardInstaller) Getting archive sizes
00:00:13.128 [INFO] (Wabbajack.Installer.StandardInstaller) Linking archives to downloads
00:00:13.128 [INFO] (Wabbajack.Installer.StandardInstaller) Found 1296 total files, 1666 matching filesize
00:00:13.202 [FATAL] (Wabbajack.Installer.StandardInstaller) Unable to download Data_ccfsvsse001-backpacks.esl (GameFileSourceDownloader+State|SkyrimSpecialEdition|1.6.640.0|data\ccfsvsse001-backpacks.esl)
00:00:13.202 [FATAL] (Wabbajack.Installer.StandardInstaller) Cannot continue, was unable to download one or more archives`

**Comment by Styyx1** [comment]
>  AVO-NG REQUIRES THE FULL PAID UPDATE TO SKYRIM. IT IS NOT/WILL NOT BE MADE COMPATIBLE WITH THE NON PAID UPDATE OR OLDER VERSIONS

you're missing the backpacks file

**Comment by tongko** [comment]
Are you referring to the CC's file in SSE folder? I'm running Steam version of AE, and having the backpack files in folder:

![image](https://user-images.githubusercontent.com/6612365/236656051-886ba106-b0eb-4229-b4cd-b8a2043504f4.png)

Not sure why the installer could not detect the file.

**Comment by Althro** [comment]
If Wabbajack fails to download any of the basegame files during the installation process, close Wabbajack, follow the steps given below, and then try running the installer again.

Step :one:
Verify the integrity of your game files through Steam, following [these steps](https://help.bethesda.net/#en/answer/25561).

Step :two:
Make sure that the game is set to English in Steam. Non-English versions of the game are not supported.

Step :three:
Open the game through Steam once to create any registry entries and INI files you don't already have, then immediately exit the launcher.

**Comment by tongko** [comment]
@Althro I follow the steps you list above, and verified that integrity of game seems OK:
![image](https://user-images.githubusercontent.com/6612365/236690265-adc88007-7ac1-4a18-a230-c4c82599e2ae.png)

The game is English:
![image](https://user-images.githubusercontent.com/6612365/236690284-7455c7ad-7ad4-4032-b2f2-21c748bd4d4c.png)

Run once to create any registry entries and INI files:
![ScreenShot0](https://user-images.githubusercontent.com/6612365/236690323-0de772df-20c3-4bb1-a2ad-a70d9232389f.png)

but result still the same...
`00:00:10.653 [ERROR] (Wabbajack.Installer.StandardInstaller) Download error for file Data_ccfsvsse001-backpacks.esl|System.NotImplementedException: The method or operation is not implemented.
   at Wabbajack.Downloaders.GameFile.GameFileDownloader.Download(Archive archive, GameFileSource state, AbsolutePath destination, IJob job, CancellationToken token) in c:\oss\wabbajack\Wabbajack.Downloaders.GameFile\GameFileDownloader.cs:line 29
   at Wabbajack.Downloaders.Interfaces.ADownloader`1.Download(Archive archive, AbsolutePath destination, IJob job, CancellationToken token) in c:\oss\wabbajack\Wabbajack.Downloaders.Interfaces\ADownloader.cs:line 26
   at Wabbajack.Downloaders.DownloadDispatcher.Download(Archive a, AbsolutePath dest, Job`1 job, CancellationToken token, Nullable`1 useProxy) in c:\oss\wabbajack\Wabbajack.Downloaders.Dispatcher\DownloadDispatcher.cs:line 102
   at Wabbajack.Downloaders.DownloadDispatcher.Download(Archive a, AbsolutePath dest, CancellationToken token, Nullable`1 proxy) in c:\oss\wabbajack\Wabbajack.Downloaders.Dispatcher\DownloadDispatcher.cs:line 48
   at Wabbajack.Downloaders.DownloadDispatcher.DownloadWithPossibleUpgrade(Archive archive, AbsolutePath destination, CancellationToken token) in c:\oss\wabbajack\Wabbajack.Downloaders.Dispatcher\DownloadDispatcher.cs:line 140
   at Wabbajack.Installer.AInstaller`1.DownloadArchive(Archive archive, Boolean download, CancellationToken token, Nullable`1 destination) in c:\oss\wabbajack\Wabbajack.Installer\AInstaller.cs:line 397
00:00:10.660 [INFO] (Wabbajack.Installer.StandardInstaller) Next Step: Hashing Archives
00:00:10.660 [INFO] (Wabbajack.Installer.StandardInstaller) Looking for files to hash
00:00:10.660 [INFO] (Wabbajack.Installer.StandardInstaller) Getting archive sizes
00:00:10.660 [INFO] (Wabbajack.Installer.StandardInstaller) Linking archives to downloads
00:00:10.660 [INFO] (Wabbajack.Installer.StandardInstaller) Found 1294 total files, 1666 matching filesize
00:00:10.745 [FATAL] (Wabbajack.Installer.StandardInstaller) Unable to download Data_ccfsvsse001-backpacks.esl (GameFileSourceDownloader+State|SkyrimSpecialEdition|1.6.640.0|data\ccfsvsse001-backpacks.esl)
00:00:10.745 [FATAL] (Wabbajack.Installer.StandardInstaller) Cannot continue, was unable to download one or more archives`

**Comment by Althro** [comment]
Follow the instructions in the readme for completely wiping the game and reinstalling.
